module TES.Data where

-- implements term rewriting systems
-- as represented in the .tes-format

import TES.Symbol
import TES.Term
import TES.Rule

import Sets
import Tree

import ToDoc
import Reader

import Parsec
import ParsecToken
import TES.Parsec


data TES = TES
	 { variables :: Set String 
	 , signature :: Signature
	 , rules :: [ Rule ]
	 }

instance ToDoc TES where
    

instance Show TES where show = render . toDoc

instance Reader TES where
    readerPrec p = do
        whiteSpace tes
        vs <- option [] $ readerPrec 0 :: Parser [ Symbol ]
	let vars =  mkSet $ map name vs

        whiteSpace tes
	rs <- many ( readerPrec 0 ) -- regeln
	let sig = sfilter ( \ s -> not (name s `elementOf` vars)) 
		$ symbols rs
        return $ TES { variables = vars , rules = rs , signature = sig }

instance Read TES where
    readsPrec = parsec_readsPrec


symbols :: [ Rule ] -> Set Symbol
symbols rules = mkSet $ do
    (l, r) <- rules
    flatten l ++ flatten r
{-* Generated by DrIFT : Look, but Don't Touch. *-}
instance ToDoc TES where
    toDocPrec d (TES aa ab ac) = docParen (d >= 10)
	      (text "TES" <+> dutch_record
	       [text "variables" <+> equals <+> toDocPrec 0 aa,
		text "signature" <+> equals <+> toDocPrec 0 ab,
		text "rules" <+> equals <+> toDocPrec 0 ac])

--  Imported from other files :-
